name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "The job was a ${{ secrets.PAT }} secrets."
      - run: echo "This job is ${{ vars.MY_NAME }} !"

      - name: Check out repository code
        uses: actions/checkout@v4
